# -*- coding: utf-8 -*-
"""finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmZRxJR6YzvnGAY0n0ywQvVHNzKIt4ZR

# Supervised Fine-Tuning

## 14. Environment and Paths

This section checks the runtime environment, mounts Google Drive, and defines the paths for:
- the saved M05 checkpoint
- the JSON instruction dataset
"""

from importlib.metadata import version

pkgs = [
    "numpy",       # PyTorch & TensorFlow dependency
    "matplotlib",  # Plotting library
    "tiktoken",    # Tokenizer
    "torch",       # Deep learning library
    "tqdm",        # Progress bar
    "tensorflow",  # For OpenAI's pretrained weights
]
for p in pkgs:
    print(f"{p} version: {version(p)}")
    # check the versions, you may get error in windows

from google.colab import drive
drive.mount('/content/drive')

model_path = "/content/drive/MyDrive/SDAIA/model.pth"

"""## 15. Loading the Instruction Dataset

This section loads the JSON dataset used for supervised fine-tuning.

### Dataset format
Each entry follows:
- `instruction`
- `input`
- `output`

This matches the project’s instruction fine-tuning requirement.

#### Adding my own JSON
"""

import json

file_path = "/content/drive/MyDrive/SDAIA/m07_instruction_data_240.json"

with open(file_path, "r", encoding="utf-8") as file:
    data = json.load(file)

print("Number of entries:", len(data))
print("Example entry:\n", data[0])

data

"""## 16. Instruction Prompt Formatting

This section defines the prompt template used for fine-tuning.

The format is:

- Instruction
- Optional Input
- Response

This helps the model learn instruction-following behavior.
"""

#keep
def format_input(entry):
    instruction_text = (
        f"Below is an instruction that describes a task. "
        f"Write a response that appropriately completes the request."
        f"\n\n### Instruction:\n{entry['instruction']}"
    )

    input_text = f"\n\n### Input:\n{entry['input']}" if entry["input"] else ""

    return instruction_text + input_text

model_input = format_input(data[50])
desired_response = f"\n\n### Response:\n{data[50]['output']}"

print(model_input + desired_response)

model_input = format_input(data[200])
desired_response = f"\n\n### Response:\n{data[200]['output']}"

print(model_input + desired_response)

"""## 17. Train / Validation / Test Split

This section splits the instruction dataset into:
- training set
- validation set
- test set

### Split used
- 85% training
- 10% test
- 5% validation
"""

train_portion = int(len(data) * 0.85)  # 85% for training
test_portion = int(len(data) * 0.1)    # 10% for testing
val_portion = len(data) - train_portion - test_portion  # Remaining 5% for validation

train_data = data[:train_portion]
test_data = data[train_portion:train_portion + test_portion]
val_data = data[train_portion + test_portion:]

print("Training set length:", len(train_data))
print("Validation set length:", len(val_data))
print("Test set length:", len(test_data))

"""## 18. Instruction Dataset Class

This section tokenizes the formatted instruction-response samples and prepares them for supervised fine-tuning.
"""

import torch
from torch.utils.data import Dataset


class InstructionDataset(Dataset):
    def __init__(self, data, tokenizer):
        self.data = data

        # Pre-tokenize texts
        self.encoded_texts = []
        for entry in data:
            instruction_plus_input = format_input(entry)
            response_text = f"\n\n### Response:\n{entry['output']}"
            full_text = instruction_plus_input + response_text
            self.encoded_texts.append(
            tokenizer.encode(full_text, allowed_special={"<|endoftext|>"})
            )

    def __getitem__(self, index):
        return self.encoded_texts[index]

    def __len__(self):
        return len(self.data)

"""## 19. Tokenizer for Fine-Tuning

This section initializes the GPT-2 tokenizer and verifies the special end-of-text token.
"""

import tiktoken
tokenizer = tiktoken.get_encoding("gpt2")

print(tokenizer.encode("<|endoftext|>", allowed_special={"<|endoftext|>"}))

def custom_collate_draft_1(
    batch,
    pad_token_id=50256,
    device="cpu"
):
    # Find the longest sequence in the batch
    # and increase the max length by +1, which will add one extra
    # padding token below
    batch_max_length = max(len(item)+1 for item in batch)

    # Pad and prepare inputs
    inputs_lst = []

    for item in batch:
        new_item = item.copy()
        # Add an <|endoftext|> token
        new_item += [pad_token_id]
        # Pad sequences to batch_max_length
        padded = (
            new_item + [pad_token_id] *
            (batch_max_length - len(new_item))
        )

        inputs = torch.tensor(padded[:-1])
        inputs_lst.append(inputs)

    # Convert list of inputs to tensor and transfer to target device
    inputs_tensor = torch.stack(inputs_lst).to(device)
    return inputs_tensor

inputs_1 = [0, 1, 2, 3, 4]
inputs_2 = [5, 6]
inputs_3 = [7, 8, 9]

batch = (
    inputs_1,
    inputs_2,
    inputs_3
)

print(custom_collate_draft_1(batch))

def custom_collate_draft_2(
    batch,
    pad_token_id=50256,
    device="cpu"
):
    # Find the longest sequence in the batch
    batch_max_length = max(len(item)+1 for item in batch)

    # Pad and prepare inputs
    inputs_lst, targets_lst = [], []

    for item in batch:
        new_item = item.copy()
        # Add an <|endoftext|> token
        new_item += [pad_token_id]
        # Pad sequences to max_length
        padded = (
            new_item + [pad_token_id] *
            (batch_max_length - len(new_item))
        )
        inputs = torch.tensor(padded[:-1])  # Truncate the last token for inputs
        targets = torch.tensor(padded[1:])  # Shift +1 to the right for targets
        inputs_lst.append(inputs)
        targets_lst.append(targets)

    # Convert list of inputs to tensor and transfer to target device
    inputs_tensor = torch.stack(inputs_lst).to(device)
    targets_tensor = torch.stack(targets_lst).to(device)
    return inputs_tensor, targets_tensor

inputs, targets = custom_collate_draft_2(batch)
print(inputs)
print(targets)

"""## 20. Collation, Padding, and Label Masking

This section:
- pads variable-length instruction samples
- builds input and target tensors
- masks ignored positions using `-100`

This is required for stable supervised fine-tuning.
"""

def custom_collate_fn(
    batch,
    pad_token_id=50256,
    ignore_index=-100,
    allowed_max_length=None,
    device="cpu"
):
    # Find the longest sequence in the batch
    batch_max_length = max(len(item)+1 for item in batch)

    # Pad and prepare inputs and targets
    inputs_lst, targets_lst = [], []

    for item in batch:
        new_item = item.copy()
        # Add an <|endoftext|> token
        new_item += [pad_token_id]
        # Pad sequences to max_length
        padded = (
            new_item + [pad_token_id] *
            (batch_max_length - len(new_item))
        )
        inputs = torch.tensor(padded[:-1])  # Truncate the last token for inputs
        targets = torch.tensor(padded[1:])  # Shift +1 to the right for targets

        # New: Replace all but the first padding tokens in targets by ignore_index
        mask = targets == pad_token_id
        indices = torch.nonzero(mask).squeeze()
        if indices.numel() > 1:
            targets[indices[1:]] = ignore_index

        # New: Optionally truncate to maximum sequence length
        if allowed_max_length is not None:
            inputs = inputs[:allowed_max_length]
            targets = targets[:allowed_max_length]

        inputs_lst.append(inputs)
        targets_lst.append(targets)

    # Convert list of inputs and targets to tensors and transfer to target device
    inputs_tensor = torch.stack(inputs_lst).to(device)
    targets_tensor = torch.stack(targets_lst).to(device)

    return inputs_tensor, targets_tensor

inputs, targets = custom_collate_fn(batch)
print(inputs)
print(targets)

logits_1 = torch.tensor(
    [[-1.0, 1.0],  # 1st training example
     [-0.5, 1.5]]  # 2nd training example
)
targets_1 = torch.tensor([0, 1])


loss_1 = torch.nn.functional.cross_entropy(logits_1, targets_1)
print(loss_1)

logits_2 = torch.tensor(
    [[-1.0, 1.0],
     [-0.5, 1.5],
     [-0.5, 1.5]]  # New 3rd training example
)
targets_2 = torch.tensor([0, 1, 1])

loss_2 = torch.nn.functional.cross_entropy(logits_2, targets_2)
print(loss_2)

targets_3 = torch.tensor([0, 1, -100])

loss_3 = torch.nn.functional.cross_entropy(logits_2, targets_3)
print(loss_3)
print("loss_1 == loss_3:", loss_1 == loss_3)

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    # Use PyTorch 2.9 or newer for stable mps results
    major, minor = map(int, torch.__version__.split(".")[:2])
    if (major, minor) >= (2, 9):
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
else:
    device = torch.device("cpu")

print("Device:", device)

print(f"Torch Version: {torch.__version__}")

"""## 21. Fine-Tuning Dataloaders

This section creates train, validation, and test dataloaders for the instruction dataset.

### Important
The maximum allowed sequence length is matched to the same context length used in the phase 1 model.
"""

from functools import partial
MODEL_CONTEXT_LENGTH = 256
customized_collate_fn = partial(
    custom_collate_fn,
    device=device,
    allowed_max_length = MODEL_CONTEXT_LENGTH
)

from torch.utils.data import DataLoader


num_workers = 0
batch_size = 8

torch.manual_seed(123)

train_dataset = InstructionDataset(train_data, tokenizer)
train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    collate_fn=customized_collate_fn,
    shuffle=True,
    drop_last=True,
    num_workers=num_workers
)

val_dataset = InstructionDataset(val_data, tokenizer)
val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    collate_fn=customized_collate_fn,
    shuffle=False,
    drop_last=False,
    num_workers=num_workers
)

test_dataset = InstructionDataset(test_data, tokenizer)
test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    collate_fn=customized_collate_fn,
    shuffle=False,
    drop_last=False,
    num_workers=num_workers
)

print("Train loader:")
for inputs, targets in train_loader:
    print(inputs.shape, targets.shape)

print(inputs[0])

"""- Similarly, we visually double-check that the targets contain the -100 placeholder tokens"""

print(targets[0])

"""## 22. Loading the Pretrained M05 Checkpoint

This section rebuilds the same GPT architecture used in M05 and loads the saved checkpoint before fine-tuning.

### Important
The model must use the exact same architecture as the saved M05 model:
- vocab size
- context length
- embedding dimension
- number of heads
- number of layers
- qkv bias setting
"""

import torch
from previous_chapters import GPTModel

# IMPORTANT:
# This config must match your saved M05 model EXACTLY.
GPT_CONFIG_124M = {
    "vocab_size": 50257,
    "context_length": 256,
    "emb_dim": 256,
    "n_heads": 8,
    "n_layers": 6,
    "drop_rate": 0.7,
    "qkv_bias": False
}

model = GPTModel(GPT_CONFIG_124M)
state_dict = torch.load(model_path, map_location="cpu")
model.load_state_dict(state_dict)

print("M05 checkpoint loaded successfully.")

MODEL_CONTEXT_LENGTH = GPT_CONFIG_124M["context_length"]

"""## 23. Base Model Behavior Before Fine-Tuning

This section generates a response from the pretrained checkpoint before supervised fine-tuning, so it can be compared later with the fine-tuned model.
"""

torch.manual_seed(123)

input_text = format_input(val_data[0])
print(input_text)

from previous_chapters import (
    generate,
    text_to_token_ids,
    token_ids_to_text
)

token_ids = generate(
    model=model,
    idx=text_to_token_ids(input_text, tokenizer).to(device),
    max_new_tokens=60,
    context_size=MODEL_CONTEXT_LENGTH,
    eos_id=50256,
)

generated_text = token_ids_to_text(token_ids, tokenizer)
print(generated_text)

"""- Note that the `generate` function we used in previous chapters returns the combined input and output text, which was convenient in the previous section for creating legible text
- To isolate the response, we can subtract the length of the instruction from the start of the `generated_text`
"""

response_text = (
    generated_text[len(input_text):]
    .replace("### Response:", "")
    .strip()
)
print(response_text)

from previous_chapters import (
    calc_loss_loader,
    train_model_simple
)

"""## 24. Baseline Loss Before Fine-Tuning

This section measures training and validation loss before instruction fine-tuning begins.
"""

model.to(device)

torch.manual_seed(123)

with torch.no_grad():
    train_loss = calc_loss_loader(train_loader, model, device, num_batches=5)
    val_loss = calc_loss_loader(val_loader, model, device, num_batches=5)

print("Training loss:", train_loss)
print("Validation loss:", val_loss)

"""## 25. Supervised Fine-Tuning

This section fine-tunes the pretrained checkpoint on the instruction dataset.

### Notes
- A smaller learning rate is used here than in M05
- This stage teaches the model to follow instructions rather than only predict the next token in raw text
"""

import time

start_time = time.time()

torch.manual_seed(123)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-5,
    weight_decay=0.01
)

num_epochs = 30

train_losses, val_losses, tokens_seen = train_model_simple(
    model,
    train_loader,
    val_loader,
    optimizer,
    device,
    num_epochs=num_epochs,
    eval_freq=5,
    eval_iter=5,
    start_context=format_input(val_data[0]),
    tokenizer=tokenizer
)

end_time = time.time()
execution_time_minutes = (end_time - start_time) / 60
print(f"Training completed in {execution_time_minutes:.2f} minutes.")

"""## 26. Fine-Tuning Loss Curves

This section plots the training and validation losses for the fine-tuning stage.
"""

from previous_chapters import plot_losses
# Alternatively:
# from llms_from_scratch.ch05 import plot_losses

epochs_tensor = torch.linspace(0, num_epochs, len(train_losses))
plot_losses(epochs_tensor, tokens_seen, train_losses, val_losses)

"""## 27. Post-Fine-Tuning Evaluation Examples

This section compares generated responses on held-out test prompts against the expected outputs.
"""

torch.manual_seed(123)


for entry in test_data[:3]:

    input_text = format_input(entry)

    token_ids = generate(
        model=model,
        idx=text_to_token_ids(input_text, tokenizer).to(device),
        max_new_tokens=256,
        context_size=MODEL_CONTEXT_LENGTH,
        eos_id=50256
    )
    generated_text = token_ids_to_text(token_ids, tokenizer)
    response_text = (
        generated_text[len(input_text):]
        .replace("### Response:", "")
        .strip()
)

    print(input_text)
    print(f"\nCorrect response:\n>> {entry['output']}")
    print(f"\nModel response:\n>> {response_text.strip()}")
    print("-------------------------------------")

"""## 28. Saving Generated Test Responses

This section saves the model responses for the test set into a JSON file for later evaluation and error analysis.
"""

from tqdm import tqdm

for i, entry in tqdm(enumerate(test_data), total=len(test_data)):

    input_text = format_input(entry)

    token_ids = generate(
        model=model,
        idx=text_to_token_ids(input_text, tokenizer).to(device),
        max_new_tokens=256,
        context_size=MODEL_CONTEXT_LENGTH,
        eos_id=50256
    )
    generated_text = token_ids_to_text(token_ids, tokenizer)
    response_text = generated_text[len(input_text):].replace("### Response:", "").strip()

    test_data[i]["model_response"] = response_text


with open("instruction-data-with-response.json", "w") as file:
    json.dump(test_data, file, indent=4)  # "indent" for pretty-printing

print(test_data[0])

"""## 29. Saving the Final Fine-Tuned Model

The final instruction-tuned model checkpoint is saved here.
"""

torch.save(model.state_dict(), "m07_finetuned_from_m05.pth")
print("Model saved as m07_finetuned_from_m05.pth")

"""## 30. Optional Ollama-Based Evaluation

This section installs and runs Ollama for optional LLM-as-a-judge evaluation.

### Note
This section is optional and is not required for the core M05 → M07 training pipeline.

####Self-Reminder: Do this only once
"""

!apt-get update -qq
!apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh
!ollama serve > /tmp/ollama.log 2>&1 &

!sleep 5
!ollama -v
!cat /tmp/ollama.log | tail -n 20

"""#####To Run ollama again"""

!pkill -f "ollama serve" || true
!nohup ollama serve >/tmp/ollama.log 2>&1 &
!sleep 5
!cat /tmp/ollama.log | tail -n 30

# !ollama pull gemma3

import json
import urllib.request

url = "http://127.0.0.1:11434/api/chat"
payload = {
    "model": "llama3",
    "messages": [
        {"role": "user", "content": "Say hello in one short sentence."}
    ],
    "stream": False
}

req = urllib.request.Request(
    url,
    data=json.dumps(payload).encode("utf-8"),
    headers={"Content-Type": "application/json"},
    method="POST"
)

with urllib.request.urlopen(req) as response:
    result = json.loads(response.read().decode("utf-8"))

print(result["message"]["content"])

!ollama pull llama3

# # 8B model
# !ollama run llama3

import psutil

def check_if_running(process_name):
    running = False
    for proc in psutil.process_iter(["name"]):
        if process_name in proc.info["name"]:
            running = True
            break
    return running

ollama_running = check_if_running("ollama")

if not ollama_running:
    raise RuntimeError("Ollama not running. Launch ollama before proceeding.")
print("Ollama running:", check_if_running("ollama"))

# This cell is optional; it allows you to restart the notebook
# and only run section 7.7 without rerunning any of the previous code
import json
from tqdm import tqdm

file_path = "instruction-data-with-response.json"

with open(file_path, "r") as file:
    test_data = json.load(file)


def format_input(entry):
    instruction_text = (
        f"Below is an instruction that describes a task. "
        f"Write a response that appropriately completes the request."
        f"\n\n### Instruction:\n{entry['instruction']}"
    )

    input_text = f"\n\n### Input:\n{entry['input']}" if entry["input"] else ""

    return instruction_text + input_text

import subprocess
import time

# Start Ollama in the background
subprocess.Popen(["ollama", "serve"])

# Give it a few seconds to initialize
time.sleep(5)

print("Ollama started in the background.")

import requests  # noqa: F811
# import urllib.request

def query_model(
    prompt,
    model="llama3",
    # If you used OLLAMA_HOST=127.0.0.1:11435 ollama serve
    # update the address from 11434 to 11435
    url="http://localhost:11434/api/chat"
):
    # Create the data payload as a dictionary
    data = {
        "model": model,
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "options": {     # Settings below are required for deterministic responses
            "seed": 123,
            "temperature": 0,
            "num_ctx": 2048
        }
    }


    """
    # Convert the dictionary to a JSON formatted string and encode it to bytes
    payload = json.dumps(data).encode("utf-8")

    # Create a request object, setting the method to POST and adding necessary headers
    request = urllib.request.Request(
        url,
        data=payload,
        method="POST"
    )
    request.add_header("Content-Type", "application/json")

    # Send the request and capture the response
    response_data = ""
    with urllib.request.urlopen(request) as response:
        # Read and decode the response
        while True:
            line = response.readline().decode("utf-8")
            if not line:
                break
            response_json = json.loads(line)
            response_data += response_json["message"]["content"]

    return response_data
    """

    # The book originally used the commented-out above, which is based
    # on urllib. It works generally fine, but some readers reported
    # issues with using urlib when using a (company) VPN.
    # The code below uses the requests library, which doesn't seem
    # to have these issues.

    # Send the POST request
    with requests.post(url, json=data, stream=True, timeout=30) as r:
        r.raise_for_status()
        response_data = ""
        for line in r.iter_lines(decode_unicode=True):
            if not line:
                continue
            response_json = json.loads(line)
            if "message" in response_json:
                response_data += response_json["message"]["content"]

    return response_data


model = "llama3"
result = query_model("What do Llamas eat?", model)
print(result)

for entry in test_data[:3]:
    prompt = (
        f"Given the input `{format_input(entry)}` "
        f"and correct output `{entry['output']}`, "
        f"score the model response `{entry['model_response']}`"
        f" on a scale from 0 to 100, where 100 is the best score. "
    )
    print("\nDataset response:")
    print(">>", entry['output'])
    print("\nModel response:")
    print(">>", entry["model_response"])
    print("\nScore:")
    print(">>", query_model(prompt))
    print("\n-------------------------")

def generate_model_scores(json_data, json_key, model="llama3"):
    scores = []
    for entry in tqdm(json_data, desc="Scoring entries"):
        prompt = (
            f"Given the input `{format_input(entry)}` "
            f"and correct output `{entry['output']}`, "
            f"score the model response `{entry[json_key]}`"
            f" on a scale from 0 to 100, where 100 is the best score. "
            f"Respond with the integer number only."
        )
        score = query_model(prompt, model)
        try:
            scores.append(int(score))
        except ValueError:
            print(f"Could not convert score: {score}")
            continue

    return scores


scores = generate_model_scores(test_data, "model_response")
print(f"Number of scores: {len(scores)} of {len(test_data)}")
print(f"Average score: {sum(scores)/len(scores):.2f}\n")

"""## 31. Error Analysis and Limitations

### Observed issues
- some prompts may produce repetitive or incomplete responses
- the model performs better on simple instruction styles than complex ones
- fine-tuning quality depends strongly on dataset coverage and consistency

### Limitations
- the model is trained on a relatively small custom setup
- context length is limited
- performance is not comparable to large production LLMs
- output quality depends on both base pretraining and SFT dataset quality

# Instant Testing
"""

from google.colab import drive
drive.mount('/content/drive')

import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")
print("Tokenizer loaded.")

"""## 33. Instant Test — M07 Fine-Tuned Model

This section runs a quick instruction-following test using the fine-tuned M07 checkpoint.

**Purpose**
- Verify that the M07 checkpoint loads correctly
- Check instruction-following behavior
- Compare against the M05 base model
"""

def format_input(entry):
    instruction_text = (
        "Below is an instruction that describes a task. "
        "Write a response that appropriately completes the request."
        f"\n\n### Instruction:\n{entry['instruction']}"
    )
    input_text = f"\n\n### Input:\n{entry['input']}" if entry["input"] else ""
    return instruction_text + input_text

# ===== Instant Test: Fine-Tuned Model (3 Examples) =====

import torch
import tiktoken
from previous_chapters import GPTModel, generate_text_simple

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = tiktoken.get_encoding("gpt2")

def text_to_token_ids(text, tokenizer):
    encoded = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
    return torch.tensor(encoded).unsqueeze(0)

def token_ids_to_text(token_ids, tokenizer):
    return tokenizer.decode(token_ids.squeeze(0).tolist())

def generate(model, idx, max_new_tokens, context_size, eos_id=None):
    return generate_text_simple(
        model=model,
        idx=idx,
        max_new_tokens=max_new_tokens,
        context_size=context_size
    )

def format_input(entry):
    instruction_text = (
        "Below is an instruction that describes a task. "
        "Write a response that appropriately completes the request."
        f"\n\n### Instruction:\n{entry['instruction']}"
    )
    input_text = f"\n\n### Input:\n{entry['input']}" if entry["input"] else ""
    return instruction_text + input_text

# Must match the same architecture used in M05/M07
GPT_CONFIG_M07 = {
    "vocab_size": 50257,
    "context_length": 256,
    "emb_dim": 256,
    "n_heads": 8,
    "n_layers": 6,
    "drop_rate": 0.7,
    "qkv_bias": False
}

# Change this path if needed
m07_model_path = "/content/drive/MyDrive/SDAIA/m07_finetuned_from_m05.pth"

m07_model = GPTModel(GPT_CONFIG_M07)
m07_state_dict = torch.load(m07_model_path, map_location="cpu")
m07_model.load_state_dict(m07_state_dict)
m07_model.to(device)
m07_model.eval()

test_entries = [
    {
        "instruction": "Who is the main character in this story?",
        "input": "One day, a little girl named Lily found a needle in her room. She asked her mother to help sew a button on her shirt. Together, they shared the needle, fixed the shirt, and felt happy because they worked together."
    },
    {
        "instruction": "How is the problem solved in this story?",
        "input": "Tim takes Sam for a ride in a loud car, and then they play together at the park."
    },
    {
        "instruction": "What is the moral of this story?",
        "input": "A little fish named Fin saw a crab that felt cold and did not want to play. Fin asked the sun to shine on the shore so the crab could feel warm again. After that, the crab felt better, thanked Fin, and they became friends."
    }
]

for i, test_entry in enumerate(test_entries, start=1):
    m07_prompt = format_input(test_entry)

    with torch.no_grad():
        m07_token_ids = generate(
            model=m07_model,
            idx=text_to_token_ids(m07_prompt, tokenizer).to(device),
            max_new_tokens=80,
            context_size=GPT_CONFIG_M07["context_length"],
            eos_id=50256
        )

    m07_generated_text = token_ids_to_text(m07_token_ids, tokenizer)
    m07_response = m07_generated_text[len(m07_prompt):].replace("### Response:", "").strip()

    print(f"===== M07 FINE-TUNED MODEL TEST {i} =====")
    print("Instruction Prompt:")
    print(m07_prompt)
    print("\nGenerated Response:")
    print(m07_response)
    print("\n" + "=" * 70 + "\n")

